# ----
# Site

title: 三十一文字
url: "https://31bot.github.io"
baseurl:
google_analytics_key: "G-TCNJMQW7QZ"
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Traditional Japanese Poems - Waka
url: 31bot.github.io
locale: ja_JP
image: /OGP.png
author:
  name:
  email:
  twitter: 31_bot
social:
  name: 31bot github
  links:
    - https://github.com/31bot
      https://twitter.com/31_bot

# -----
# Build

timezone: Tokyo/JST

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release


types:
  - minor
  - major



languages: ["ja"]
