# ----
# Site

title: 三十一文字
url: "https://31bot.github.io"
baseurl:
google_analytics_key: "G-TCNJMQW7QZ"
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Traditional Japanese Poems - Waka
url: https://31bot.github.io
locale: ja_JP
author:
  name:
  email:
  twitter: 31_bot
social:
  name: 三十一文字bot
  links:
    - https://github.com/31bot
    - https://twitter.com/31_bot
    - https://bsky.app/profile/31bot.bsky.social

# -----
# Build

timezone: Tokyo/JST

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE


defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      image: https://31bot.github.io/OGP.png
      locale: ja_JP
  -
    scope:
      path: ""
    values:
      layout: single-layout
      image: https://31bot.github.io/OGP.png
      locale: ja_JP


types:
  - minor
  - major



languages: ["ja"]


collections:
  kokinwakashu:
    order:
      - preface.md
      - vol1.html
      - vol2.html
      - vol3.html
      - vol4.html
      - vol5.html
      - vol6.html
      - vol7.html
      - vol8.html
        - 365.html
        - 366.html
        - 367.html
      - vol9.html
      - vol10.html
      - vol11.html
      - vol12.html
      - vol13.html
      - vol14.html
      - vol15.html
      - vol16.html
      - vol17.html
      - vol18.html
      - vol19.html
      - vol20.html
      - bokumetsuka.html
    output: true
  gosenwakashu:
    output: true